### ISSUE TITLE
still_picture =1 should not be a requirement for image sequences

### ISSUE THREAD

**Issue by aklemets** [AOMediaCodec/av1-avif#12]
When HEVC is used in a HEIF image sequence, non-IDR frames are allowed. I would expect the same to be allowed with AV1.

**Comment by cconcolato** [comment]
I'm wondering what would be the difference then between an image sequence and a video sequence? Should it be restricted to not containing any `show_frame = 0` (i.e. the equivalent of b-frames).

**Comment by cconcolato** [comment]
More broadly, as discussed during today's AOM Image call:
- Is there a reason to have a difference between a video sequence and an image sequence (besides profiles that can be handled by brands)? 
- Should we simply say that an image sequence is a video sequence? 
There might be optimizations that can be done in decoders (e.g. memory consumption) when processing only intra frames.
Maybe we should handle such limitations in profile definitions.

**Comment by aklemets** [comment]
As I recall, for HEVC in HEIF, there is no significant difference between an image sequence track and a video track. The timestamps for the image sequence track are “advisory”, meaning that a client is not required to strictly adhere to timing when playing the image sequence track.

Also, there are additional boxes to help the client decode P/B image frames in an image sequence track. There is a “Direct Reference” Sample Group box which specifies which other frames have to be fed to decoder first, before the desired image frame can be decoded. (The box also specifies if a frame can be decoded independently of any other frames.) These boxes are part of the base HEIF spec, so they should apply to AV1 as well.

Anders

________________________________

**Comment by garysull** [comment]
Agreeing with Anders here, HEIF can contain coded media things, each of which is identified as an "image", "image collection", or "image sequence" (along with audio and other stuff). Each picture is independently coded if it is an "image" or part of an "image collection", and for AVC and HEVC, "image sequences" can use inter-picture prediction if desired by the encoder. I don't see why this should be different for AV1. There could certainly be a big coding efficiency benefit for using inter-picture prediction for "image sequences" in some uses. I believe there is also no prohibition of non-output pictures or out-of-order output pictures for HEVC, and offhand I don't see a reason to prohibit them for AV1. (I think there is some imprecision in some of the above comments about what a B frame is; in AVC and HEVC, a B frame is not entirely the same as it was in MPEG-2.)

If it would be preferable for the pictures to be independently decodable in some use case, is there a reason that use case couldn't use an "image collection" rather than an "image sequence"?

**Comment by agrange** [comment]
It seems to me that an "image sequence" is really just a "coded video
sequence" and can deploy the full capabilities of the AV1 bitstream.

It is the fact that it is wrapped up in an "image sequence track" rather
than a "video track" that tells the decoder that timestamps are advisory.

How are "image sequence tracks" handled from the leveling perspective? I
assume the level/tier signaled in the sequence header would be expected to
be respected?

**Comment by agrange** [comment]
AV1 does not define separate levels for still pictures. Presumably an image
sequence track would ignore the "real-time" aspects of the level
definition, whereas the video track enforces it in full. This will make the
level definition more usable and result in fewer sequences being tagged as
level = 31.

**Comment by cconcolato** [comment]
Do you mean that:
- for image sequence tracks, if the decoder model is applied, only the resource availability mode matters?
- and that for level 31, the decoding model must operate in resource availability mode?

**Comment by agrange** [comment]
No - because resource availability mode still checks that the decoder can
keep up with a display rate. No such rate is defined for an image sequence
track (correct?).

The intention of level 31, IIRC, was that it is a "best efforts" approach.
The decoder will do its best but there are no guarantees.

**Comment by cconcolato** [comment]
Discussed during AOMI meeting.

There is no difference in AVIF between an image sequence and a video sequence. 
As defined in ISOBMFF/HEIF, the use of 'pict' indicates advisory timing, while the use of 'vide' track handler indicates timing is mandatory.
The general section of the specification should not constrain the contents of a track. Profiles, identified by brands may do that, e.g. saying that inter-prediction is not used.
