### ISSUE TITLE
AVIF color Profile RGB

### ISSUE THREAD

**Issue by Shanti099** [AOMediaCodec/av1-avif#126]
AVIF color Profile RGB

Hello,

Would you please add the ability to convert images while maintaining the sRGB color space, by default, AVIF uses the YUV color space, which distorts the color of photos, and has a more limited color range.
This distorts the color of the photos and makes this format unacceptable for converting photos.

Thank you

**Comment by leo-barnes** [comment]
Hi,

With regards to color spaces, AVIF does pretty much the same thing as JPEG. A color space can be signaled via an ICC profile (or CICP code points in AVIF), with sRGB being the default if nothing is specified. 

The actual pixels can be stored as either YUV with various subsamplings or RGB. YUV is the "default" since it's much more efficient with regards to compressed size. In AVIF, coding as RGB is done by using the identity matrix for YCbCr matrix. In JPEG, you need to use the Adobe APP14 segment to signal that no transform should be used.

Can you give some more clarification on what your exact use-case is? If you're using AVIF as a replacement for JPEG there shouldn't be any features missing as far as I'm aware.

**Comment by leo-barnes** [comment]
No reply from originator and no clear action item to be implemented until we know more. Closing for now.

@Shanti099, feel free to re-open if you think something is missing from the spec.
