### ISSUE TITLE
reduced_still_picture_header must be set to 0 for scalable images

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/av1-avif#133]
Because reduced_still_picture_header forces the frame type to be a KEY_FRAME (and therefore all intra), it cannot be set for the dependent images in a scalable / progressive image. However, the current AVIF spec has in section 2.1:

> The AV1 Image Item Data should have its reduced_still_picture_header flag set to 1.

I suggest simply removing this line, allowing either 1 or 0 in AVIF.

**Comment by wantehchang** [comment]
All the frames are in the same AV1 coded video sequence (otherwise they cannot be in the same operating point or depend on each other), so they share the same reduced_still_picture_header syntax element in the sequence header OBU.

We may also need to set the still_picture syntax element to 0. Section 6.4.1 of the AV1 specification says:

> **still_picture** equal to 1 specifies that the coded video sequence contains only one coded frame. still_picture equal to 0
> specifies that the coded video sequence contains one or more coded frames.

**Comment by tdaede** [comment]
Yes, I just checked and libaom validates this, and produces the following error:

> Warning: Failed to decode frame 1: Corrupt frame detected
> Warning: Additional information: Still pictures must be coded as shown keyframes

So we will need to drop the still_picture requirement as well.
