### ISSUE TITLE
Add additional restriction to colr box from HEIF DAmd2

### ISSUE THREAD

**Issue by joedrago** [AOMediaCodec/av1-avif#164]
The next version of HEIF will make it legal for a file to simultaneously have one `colr` box of each `colour_type`. This is fantastic as it allows for CICP to live alongside an ICC profile at the container level, but creates a potential _legal_ file that is actually functionally confusing. 

The three `colour_type`s are: 
* `nclx` - CICP and the range flag
* `rICC` - "Restricted" ICC profile
* `prof` - "Unrestricted" ICC profile

I suspect the nuanced distinction between `rICC` and `prof` are not really useful in practice, but if this additional bit of information is meaningful to someone, that's fine. However, I don't think it is a worthwhile feature to support an AVIF containing two embedded ICC profiles (one `rICC` and one `prof`). Supporting this wasn't the original intent with DAmd2's change, and we should just be explicit about it in AVIF for now.

I'm not sure exactly how to word it, but I think the easiest and most practical restriction would simply to make `rICC` and `prof` mutually exclusive properties on a given item. This would allow for the distinction between the two ICC `colour_type`s to continue to exist for those that want it in AVIF, and it would allow `nclx` to coexist with either of them.

**Comment by baumanj** [comment]
The main question I'd have is whether this is a hard requirement (and readers should reject the files rather than render something ambiguous) or a recommendation. 

My suggestion for the wording would be:

> Quantity (per item): Up to two: at most one for a `colour_type` value of `'nclx'` and at most one one for a value of `'rICC'` or `'prof'`, but not both.

I also think it's important that we add both valid and invalid examples of `colr` boxes to https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles. Currently there aren't any examples with multiple `colr` property associations per image, nor any with `colour_type` values other than '`nclx`'.

**Comment by leo-barnes** [comment]
@cconcolato @baumanj 
Did we ever file an issue for MPEG?

> Quantity (per item): Up to two: at most one for a colour_type value of 'nclx' and at most one one for a value of 'rICC' or 'prof', but not both.

I think the sentence would be clearer by removing `, but not both`

The `but not both` part feels like it confuses matters to me. I can't pinpoint exactly why, but I guess it's hard to say exactly which part of the sentence it refers to given that you have two groups described (`nclx` vs `rICC`/`prof` and `rICC` vs `prof`).

**Comment by baumanj** [comment]
>  Did we ever file an issue for MPEG?

No, is https://github.com/MPEGGroup/FileFormat/ the right place for that since it's HEIF?

> I think the sentence would be clearer by removing `, but not both`

Yeah, I struggled with the most concise, but clear way to say it. Upon further thought, I think the best thing would be even a bit _more_ restrictive. Even though it's a bit strange it eliminates a potentially ambiguous situation:

> Quantity (per item): 0, 1 (unrestricted) or 2 (with restrictions):
> - One for a `colour_type` value of 'nclx', 'rICC' or 'prof'
> - One for a `colour_type` value of 'rICC' or 'prof' and for a `colour_type` value of 'nclx'
with `colour_primaries = 2` and `transfer_characteristics = 2` (2 indicating "unspecified", since these data are supplied by the ICC profile instead)

**Comment by podborski** [comment]
> > Did we ever file an issue for MPEG?
> 
> No, is https://github.com/MPEGGroup/FileFormat/ the right place for that since it's HEIF?
> 

Yes, you can just use label `HEIF` in that case.

**Comment by wantehchang** [comment]
Jon's new suggestion for the wording is a little verbose but very precise. I suggest adding the word "one" before "for a `colour_type` value of 'nclx'".

**Comment by cconcolato** [comment]
Note that the corresponding MPEG issue https://github.com/MPEGGroup/FileFormat/issues/39 has been closed because the proposed wording was added to an ongoing HEIF amendment. 
AVIF does not reference a specific, dated version of HEIF, so when the amendment gets published, it will apply to AVIF files. The current timeline of the MPEG amendment is: should reach FDAM status in the MPEG October meeting, and then should be officially published by ISO end of year.

**Comment by leo-barnes** [comment]
I think this can be closed per @cconcolato's comment.
