### ISSUE TITLE
"This version" link doesn't work as expected

### ISSUE THREAD

**Issue by agrange** [AOMediaCodec/av1-avif#179]
The field "This version" link in the various versions of the spec all link to the latest version, rather then the expected version of the sped.

**Comment by cconcolato** [comment]
Should we have a "This version" and a "Latest version"?

**Comment by wantehchang** [comment]
Yes. We can put the "Latest version" link near the "Previously approved version" link.

**Comment by leo-barnes** [comment]
I think this is now working as intended. I do notice that the "Latest draft" link does not seem to work. Presumably this is because latest-draft.html is a symbolic link pointing to a file that does not exist. I see that the gh-pages branch did not get that file when it grabbed the commit where it was added. Presumably it strips broken symbolic links.

After thinking on it a bit, I think we should change this into having:
1. "This version" (points to latest draft if it is a draft, points to specific version once published)
2. "Latest version" (points to the latest document available, draft or published)
