### ISSUE TITLE
Should AVIF files contain at most one EXIF blob and at most one XMP blob?

### ISSUE THREAD

**Issue by y-guyon** [AOMediaCodec/av1-avif#193]
According to [AVIF](https://aomediacodec.github.io/av1-avif/), MIAF (ISO 23000-22:2019) and HEIF (ISO 28002-12:2021) specifications, it is possible to have multiple EXIF blobs and multiple XMP blobs in an AVIF file.

@wantehchang raised the following question: should it be allowed? I imagine most tools only support one metadata blob of each kind. The constraint could be put on the `infe` box, at the HEIF, MIAF or AVIF level.

Current situation:

- libavif API: Encode only one EXIF and only one XMP. Decode only one EXIF and only one XMP.
- libheif API: Encode any count of EXIF and any count of XMP. Decode any count of EXIF and any count of XMP.
- libwebp API: Encode only one EXIF and only one XMP. Decode any count of EXIF and any count of XMP.
- [WebP specification](https://developers.google.com/speed/webp/docs/riff_container):
    > There SHOULD be at most one chunk of each type ('EXIF' and 'XMP '). If there are more such chunks, readers MAY ignore all except the first one. Also, a file may possibly contain both 'EXIF' and 'XMP ' chunks.

Related: https://github.com/AOMediaCodec/libavif/issues/825

I found 243 files on 63240 crawled AVIF images that had two EXIF chunks according to libheif (`heif_context_get_primary_image_handle()` + `heif_image_handle_get_list_of_metadata_block_IDs()` + `heif_image_handle_get_metadata_type()`). [Image example](https://jakekara.com/assets/images/avif/VisualSearch-300.avif) (use [mp4box.js](https://gpac.github.io/mp4box.js/test/filereader.html)).

Note: I did not check for ICC blobs, maybe there is the same issue.

**Comment by leo-barnes** [comment]
> I imagine most tools only support one metadata blob of each kind.

Are you sure? We certainly support multiple EXIF and XMP blobs for HEIC files. I would expect libheif to also do so.

> should it be allowed?

I think so, yes.

For XMP, there are definitively fully defined use-cases that benefit from having multiple XMP blobs. Example:
You want to transcode a JPEG that contains IPTC and XMP to HEIF/AVIF. Unless you go down the route of using the `uri` boxes for storing IPTC IIM, you will need to convert the IPTC to XMP. The most natural way of storing this in the HEIF/AVIF would be as one XMP blob containing the IPTC and one containing the XMP from the JPEG. Trying to merge the IPTC-XMP and original XMP blob into a single blob is probably possible, but seems like it 

Having multiple EXIF blobs is a bit more confusing and could probably benefit from having the *SHOULD* from WebP to tell decoders what the recommended way of handling it is. But I can definitely imagine that some proprietary image processing system might want to be able to store both a modified EXIF blob as well as the original blob in a file. Just because it's not useful on the web doesn't mean that it's not useful at all 😃.

**Comment by wantehchang** [comment]
Leo,

Thank you for your comment.

Since AVIF is based on MIAF and MIAF defines "additional constraints on ISO/IEC 23008-12 (HEIF) specification, to simplify its file format options" and "to ensure higher interoperability", imposing additional constraints on Exif and XMP metadata to simplify their processing by applications is in the spirit of MIAF.

We have seen applications assume at most one Exif metadata item and at most one XMP metadata item per image. This simplistic assumption seems widespread. Therefore, it is the right trade-off to make the producer of an AVIF file do more work to merge Exif metadata items or XMP metadata items so that all consumers of the AVIF file can do less work. Also, merging metadata items of the same type will eliminate duplicate entries, which not only reduces the file size (after all, AVIF is an image compression format) but also avoids conflicting values.

Our (Google's) internal customer who asked about storing IPTC IIM in AVIF decided to do the right thing -- convert IPTC IIM to XMP and merge it with any original XMP metadata. I imagine that an application that can convert IPTC IIM to XMP should also be able to merge two XMP metadata items. Therefore it doesn't seem mandatory to support the IPTC-XMP + original XMP use case.

**Comment by leo-barnes** [comment]
@wantehchang 
> Since AVIF is based on MIAF and MIAF defines "additional constraints on ISO/IEC 23008-12 (HEIF) specification, to simplify its file format options" and "to ensure higher interoperability", imposing additional constraints on Exif and XMP metadata to simplify their processing by applications is in the spirit of MIAF.

Right, but that is also kind of why I'm objecting to putting hard constraints on it. I can see multiple potential use-cases for having multiple Exif and XMP blobs in file. Having a hard restriction on it in MIAF means AVIF can **never** be used for those use-cases since AVIF has no way of falling back to HEIF.

I'm all for having something like the snippet WebP has, since that tells parsers what they should do if they don't have any additional information. But I don't want to disallow potential proprietary/closed-system use-cases either. The only thing doing so will lead to is for people to start doing hacky things to work around it.

---------------

As a related example, consider image collections. It's not exactly defined what a parser/renderer should do if it encounters a file with multiple images that are not in some kind of HEIF group that explains what they should be used for. But in the case of macOS desktop pictures, the situation that the file is used in (along with some metadata in the file) tells us that the various images in the file should be displayed at specific times of day. This use-case is probably way too narrow to be useful to standardize, but the fact that the underlying image format is flexible means that it can be accomplished without having to create some custom file format, create non-compliant files or mess around with folders of image files and similar.

**Comment by y-guyon** [comment]
As discussed, there is no need to handle multiple XMP nor EXIF chunks in libavif. libheif can be used for this rather specific use case.
