### ISSUE TITLE
AVIF and audio/video; create a normal format like "AOM" (AOMedia)

### ISSUE THREAD

**Issue by corzid** [AOMediaCodec/av1-avif#3]
AVIF is based on HEIF, which means it can also contain audio (sic!) and subtitles. Why not make a new format and name it like AOM (AOMedia)? AV1 for video, AA1 for audio, AS1 for subtitles. Yes, you will need to re-invent, but you will immediately make a normal format, which will not be embarrassing to let in the masses. There will be a single ecosystem that does not oblige to support all that obsolete garbage from the WEBM.

Wishes:
1. Thumbnail should be encoded AV1, why do you need JPEG here?
2. At the beginning of the file (magic number) you can use "aom". And then add "a" if file contain audio, "v" for video, "s" for subtitles. The order of additional designations is exactly what was called earlier ("avs").
3. Would not prevent a gradual download, as in the FLIF format. It would be nice to do this by default, but it's already impossible, right? AV1 is already standardized...
4. Try to make the design of the format more minimalistic, you do not need to do "if it's here, then there, otherwise in other places". Be simpler.
5. Be doubly simpler. You do not need to support all possible metadata formats. (Make your own, but well-thought-out. Meow.)
6. Force it on the web.

Let's do better than HEVC, PNG, JPEG, GIF, FLIF, ASS (SSA) and any audio format. We will reconsider everything that we have done before, we will do better. And we will spread this format by all means, because AOMedia contains companies that everyone has heard.

**Comment by cconcolato** [comment]
> AVIF is based on HEIF, which means it can also contain audio (sic!) and subtitles.

Are you concerned with the impact on players? They can simply ignore that if they want.

> Why not make a new format and name it like AOM (AOMedia)? AV1 for video, AA1 for audio, AS1 for subtitles.

This is out of scope of this activity, which is focused on images. If you are interested in that, I suggest you bring this point to AOM.

> Thumbnail should be encoded AV1, why do you need JPEG here?

Good question. JPEG support is ubiquitous so that should not be a problem. Also, decoding complexity with JPEG for thumbnails could be lower than for AV1. I think initially this was for compatibility with MIAF. 

> At the beginning of the file (magic number)

ISOBMFF on which HEIF/MIAF and this spec are based does not have "magic number", it uses the "ftyp" box to list compatibility brands.

> Would not prevent a gradual download, as in the FLIF format. It would be nice to do this by default, but it's already impossible, right? AV1 is already standardized...

I don't get this point. The MIAF brand 'MiPr' supports progressive download.

> Try to make the design of the format more minimalistic, you do not need to do "if it's here, then there, otherwise in other places". Be simpler.

We're trying to balance 1) addressing the various use cases 2) compatibility with other formats to leverage existing tools and 3) simplicity.

**Comment by cconcolato** [comment]
Closing as it seems that most of the comments are broader than AVIF. Please open separate issues on AVIF specifically if you have concerns or bring broader comments to AOM.
