### ISSUE TITLE
Potential fragmented-only decoder contraint

### ISSUE THREAD

**Issue by jaikrishnan** [AOMediaCodec/av1-avif#64]
Based on the AOM call and discussion on the [Chrome bug for AVIF](https://bugs.chromium.org/p/chromium/issues/detail?id=960620#c33), there may be interest in allowing a constrained decoder to only support AVIF in fragmented MP4, as opposed to requiring unfragmented MP4 support. 

This could be similar to the way the decoder constraint for reduced / intra-only tooling is handled. Not sure if a flag is required or if the file can simply be inspected.

**Comment by aklemets** [comment]
MIAF already defines brands for this. Since AVIF is defined on top of MIAF, the same brands could be used in an AVIF file. The “brands” are codec-independent (unlike MIAF “profiles”, which are tied to HEVC.) So, AVIF can use MIAF “brands” but not the “profiles”.

There are three relevant brands:

'MiCm' – This indicates that the image sequences use only fragmented tracks and that those tracks are compatible with CMAF (Common Media Application Format for Segmented Media, ISO/IEC 23000-19)

‘MiAn’ – This brand is for animations. There is exactly one image track or video track, and 0 or 1 alpha tracks, and 0 or 1 audio tracks.

'MiAC' – This brand indicates that the animation has an associated alpha plane track. The ‘MiAn’ and 'MiCm' brands are required to be specified. So, it means that that all the tracks are fragmented. As a further restriction, the animation track must be a video track (not a picture track).

Anders

________________________________

**Comment by jaikrishnan** [comment]
So would a potential resolution would be to create one or more AVIF profiles which support a subset of these brands?

**Comment by aklemets** [comment]
I think these brands can already be used today in AVIF files. For example, an AVIF file can be tagged 'MiCm' to indicate that all the tracks are Fragmented.

However, I am not sure exactly what that solves – by the time the AVIF parser has inspected the brands, it has already started downloading the AVIF file, at which time it can easily determine if tracks are fragmented, or not, by parsing the rest of the file.

I think that to be really useful, the fact that all tracks are fragmented has to be stated up-front, before the client downloads the file. This could be done by specifying the brand as parameters to the MIME type (as is done in MPEG-DASH streaming scenarios), or by using a completely different MIME type (e.g., image/avif-fragmented-sequence).

Anders

**Comment by dalecurtis** [comment]
Yeah, not sure this is all that helpful. It would only be useful if we required all AVIF to be fragmented or not fragmented, instead of letting AVIF encompass the full scope of possibilities for an MP4 container :|

**Comment by jaikrishnan** [comment]
I'm ok closing this if no one else is interested in this distinction.

**Comment by dalecurtis** [comment]
Yeah, I think the ship has sailed on this unfortunately. Unless you want to change the AVIF spec to require fragmentation then I don't think there's any utility here.

@joedrago in case he has a different opinion.

**Comment by jaikrishnan** [comment]
closing based on discussion consensus that this feature would not be used
