### ISSUE TITLE
How about additional constraints: "All frames in Image Sequence file should have the same size (widthxheight)"

### ISSUE THREAD

**Issue by ledyba-z** [AOMediaCodec/av1-avif#75]
Hi. I am currently supporting AVIF/AVIFS images in Chrome, and implementing AVIFS in [cavif](https://github.com/link-u/cavif) and [davif](https://github.com/link-u/davif).

According to Wan-Teh, a chrome developer, it is required to all frames in an animated image to be the same size in Chrome(widthxheight).

I think it's reasonable constraints.

FYI: In WebP, it looks all frame have the same size.
https://github.com/webmproject/libwebp/blob/master/src/webp/mux.h#L277-L312

**Comment by ledyba-z** [comment]
Via https://github.com/AOMediaCodec/libavif/issues/112, I understand that AVIS can contain not only key frame, but also I frame.
In other words, AVIS just contains normal AV1 video stream.
(Previously, I imagine that AVIS consists multiple AV1 Key frames)

Thus, currently, each frame of Image Sequence can have different width or height (because frameWidth and frameHeight can be override in Frame Header OBU).

Is my understanding correct?

**Comment by novomesk** [comment]
I am just a hobby programmer (and libavif user). In my [qt-avif-image-plugin](https://github.com/novomesk/qt-avif-image-plugin) I expect that all images in AVIFS file have same dimension. Otherwise I consider it an error.
This is what I concluded from: https://github.com/AOMediaCodec/libavif/issues/35#issuecomment-564665958

**Comment by cconcolato** [comment]
We will raise an issue on the AV1 spec to get clarification on the behavior of video sequences with changing resolutions.

**Comment by leo-barnes** [comment]
After discussing this some more with Cyril, a 4th alternative is to suggest the following change to MIAF since this applies to other codecs as well:
a) Addition of new brand for files that contain tracks with varying frame dimensions
b) Files containing tracks with varying frame dimensions shall use the brand from a)
c) Parsers that do not support a) may reject decoding those tracks

So we now have 4 alternatives in total:

1. leave the spec as is - makes it harder for implementation
2. change the spec to restrict images to have the same decoded width/height - is a breaking change
3. allow signaling (e.g. with an additional brand) that all images have the same width/height
4. Suggest that MIAF adds brand and that files missing the brand may not have varying frame dimensions.

**Comment by leo-barnes** [comment]
I prefer option 4 since it's a problem not only for AVIF. It makes the default implementation easy, but leaves the option of using varying frame sizes there if someone really wants it.

**Comment by cconcolato** [comment]
The agreement is to change AVIF (option 2) and to discuss with MPEG to do option 4.

**Comment by cconcolato** [comment]
I have implemented the proposed change https://github.com/AOMediaCodec/av1-avif/pull/99
I have some questions:
- AV1 video-specific: I used the term FrameWidth and FrameHeight. Is this the right way to phrase the constraint? FrameWidth/Height are variables that are modified during the decoding process. Should the spec say FrameWidth/Height after decoding or is it clear?
- Container-specific: The width and height of images is exposed (actually the max of) in the sample description entry. So we could envisage restricting the number of sample description entries to 1. Or is it too restrictive?

**Comment by wantehchang** [comment]
Cyril wrote:
>
> I have some questions:
> 
> * AV1 video-specific: I used the term FrameWidth and FrameHeight. Is this the right way to phrase the constraint? FrameWidth/Height are variables that are modified during the decoding process. Should the spec say FrameWidth/Height after decoding or is it clear?

If you want to use the variables from the AV1 spec, you can use either
- RenderWidth and RenderHeight; or
- UpscaledWidth and FrameHeight.

The FrameWidth variable in the AV1 spec may be different from the width of the decoded output frame. That value is represented by the UpscaleWidth variable. UpscaledWidth can be calculated after parsing the AV1 frame header OBU, without decoding the frame.

**Comment by wantehchang** [comment]
I found that ISO BMFF specifies how to handle an image sequence whose image sizes differ from the size in the TrackHeaderBox. Section 8.3.2.3 of ISO BMFF says:

>   width and height fixed‐point 16.16 values are track‐dependent as follows:
> 
>     For text and subtitle tracks, they ...
> 
>     For non‐visual tracks (e.g. audio), they ...
> 
>     For all other tracks, they specify the track's visual presentation size. These need not be the same
>     as the pixel dimensions of the images, which is documented in the sample description(s); all
>     images in the sequence are scaled to this size, before any overall transformation of the track
>     represented by the matrix. The pixel dimensions of the images are the default values.

Note that it says "all images in the sequence are scaled to this size". Now that I know how an image sequence of varying image sizes should be handled, it is fine by me to close this issue with no action.

Note: I am planning to leave the current constraint in Chrome until we actually run into an AVIF image sequence with varying image sizes.

**Comment by cconcolato** [comment]
Discussed today and agreed to close without action.
