### ISSUE TITLE
Simpler, smaller header metadata

### ISSUE THREAD

**Issue by kornelski** [AOMediaCodec/av1-avif#94]
Would it be possible to make `iinf`, `pitm`, and especially `iloc` optional?

For a single image with single contiguous data chunk these boxes are redundant. `iloc` is especially cumbersome to generate, since offset in the box depends on the size of the box and all surrounding metadata.

**Comment by cconcolato** [comment]
Thank you for the feedback.

The purpose of the `pitm` box is to let the author indicate which item they think is the primary, when there are multiple images in the file (e.g. burst of images, or thumbnails ...). It could have been avoided in the case of single image files (saving 14 bytes). It is rather simple to write though: one 2-byte field.

The purpose of the `iinf` box is to provide a mapping from the item id to essential information such as its type. Remember that the core formats (ISOBMFF or HEIF) are codec-agnostic. HEIC (HEIF+HEVC) uses the same format that AVIF, so it is important to identify the item type / codec. When using `infe` v2 or v3, each entry is rather simple I think. You have 3 fields to process: id, type, name. The name can also be useful for item manipulation by name.

The `iloc` provides the offset and size of the image. It has advantages in complex cases (e.g. when you want to fetch the image without fetching the entire file (e.g. when the file also contains a large video also in a mdat); or when you image contains several layers, ...). I agree it can be tricky to write. Different strategies can be used: 
- write the mdat upfront so that you know its offset when writing the iloc, 
- pad the file header (e.g. with a `free` box) to keep the mdat always at the same offset (if the file size increase is not an issue), 
- keep a pointer to where the offset is written and come back after writing the image to update it
- ...

I agree that in the case of a simple file (no other image, no other information, fixed codec) the format could have omitted them. How often are those files so simple? Note that Exif metadata is also stored as an item. Thumbnails too, which are fairly common. Also having the syntax always the same makes the behavior of readers more homogeneous between the simple case and the less simple case. Less testing. These may not be killer arguments, I confess.

Anyway, if you (or others) think that changes to these boxes are worthwhile, I'm open to discussions. Doing the change in AVIF only would mean losing compatibiltiy with MIAF/HEIF/ISOBMFF, which we probably don't want. The change should probably be done in the base format (not in AVIF only). In that case, I would suggest raising an issue at https://github.com/MPEGGroup/FileFormat (cc @dwsinger).

**Comment by kornelski** [comment]
I was thinking about Web use-cases, where a single simple image is the norm, and metadata is often highly undesirable. EXIF is considered an unnecessary overhead to be optimized out, and even a danger to privacy, because it may contain GPS info.

I imagined that a file with just `ftyp` of `avif` and `mdat` would be enough to display a single opaque image (i.e. in absence of `pitm` and `iloc` assume there's just only one image, it's primary, and takes whole `mdat`). For the Web, that's all that is needed. It would make AVIF much more similar to JPEG's and PNG's minimal structure.

Unfortunately, the roundabout specification of alpha channel in AVIF makes all of this much more complicated. I don't see a solution to embedding alpha nicely without deviating from fundamentals of HEIF or changing AV1 bistream, so I guess I'll have to live with `iloc` :(
